export const SET_CRAFT_ORDER_OPTIONS = 'SET_CRAFT_ORDER_OPTIONS';
export const SET_NEW_ORDER_SIZE = 'SET_NEW_ORDER_SIZE';
export const SET_NEW_ORDER_PAPER = 'SET_NEW_ORDER_PAPER';
export const SET_NEW_ORDER_CORNER = 'SET_NEW_ORDER_CORNER';
