export const SET_FRONT_IMAGE_URL = 'SET_FRONT_IMAGE_URL';
export const SET_UPLOAD_IMAGE_STEP = 'SET_UPLOAD_IMAGE_STEP';
export const SET_FRONT_IMG_COORD = 'SET_FRONT_IMG_COORD';
export const UPDATE_FRONT_COORD = 'UPDATE_FRONT_COORD';
export const SET_NEW_CANVAS_ORIENTATION = 'SET_NEW_CANVAS_ORIENTATION';
